spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: false
      auto-offset-reset: latest
    listener:
      ack-mode: manual

server:
  port: 9000

RMS:
  kafka:
    topic: AlarmFieldEnum7



